;
; File generated by cc65 v 2.15 - Git 51bcf28
;
	.fopt		compiler,"cc65 v 2.15 - Git 51bcf28"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_foo
	.export		_main

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; write_addr(0x2000, 0);
;
	jsr     decsp2
	lda     #$00
	sta     $2000
;
; write_addr(0x2001, 0);
;
	sta     $2001
;
; write_addr(0x2006, 0x3f);
;
	lda     #$3F
	sta     $2006
;
; write_addr(0x2006, 0x00);
;
	lda     #$00
	sta     $2006
;
; write_addr(0x2007, 0x0C);
;
	lda     #$0C
	sta     $2007
;
; write_addr(0x2007, 0x17);
;
	lda     #$17
	sta     $2007
;
; write_addr(0x2007, 0x28);
;
	lda     #$28
	sta     $2007
;
; write_addr(0x2007, 0x39);
;
	lda     #$39
	sta     $2007
;
; write_addr(0x2006, 0x21);
;
	lda     #$21
	sta     $2006
;
; write_addr(0x2006, 0xca);
;
	lda     #$CA
	sta     $2006
;
; for(i=0;i<100;++i) {
;
	ldy     #$00
	tya
	sta     (sp),y
	iny
	sta     (sp),y
L0020:	ldy     #$01
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	cmp     #$64
	txa
	sbc     #$00
	bvc     L0027
	eor     #$80
L0027:	asl     a
	tya
	bcc     L0045
;
; write_addr(0x2007, foo[i]);
;
	lda     #<(_foo)
	clc
	adc     (sp),y
	sta     ptr1
	lda     #>(_foo)
	iny
	adc     (sp),y
	sta     ptr1+1
	dey
	lda     (ptr1),y
	sta     $2007
;
; for(i=0;i<100;++i) {
;
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
	jmp     L0020
;
; write_addr(0x2006, 0x00);
;
L0045:	sta     $2006
;
; write_addr(0x2006, 0x00);
;
	sta     $2006
;
; write_addr(0x2005, 0x00);
;
	sta     $2005
;
; write_addr(0x2005, 0x00);
;
	sta     $2005
;
; write_addr(0x2000, 0x90);
;
	lda     #$90
	sta     $2000
;
; write_addr(0x2001, 0x1e);
;
	lda     #$1E
	sta     $2001
;
; for(;;);
;
L0041:	jmp     L0041

.endproc

